import musketeer

filename = f"dist/Musketeer-{musketeer.__version__}-macOS.dmg"
volume_name = "Musketeer"
format = "UDZO"
filesystem = "HFS+"
size = None
files = ["dist/Musketeer.app"]
symlinks = {"Applications": "/Applications"}
badge_icon = "logo 512px.icns"
background = None
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
show_icon_preview = False
include_icon_view_settings = "auto"
include_list_view_settings = "auto"
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = "bottom"
text_size = 16
icon_size = 128
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
